### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by pdemanget** [lauterry/MyAngularMovieLibrary#1]
Bonjour,
J'aimerais utiliser un élément de ce projet pour mes propres tutoriels: le fichier web-server.js

ëtes-vous l'auteur de ce fichier et si oui, quelle licence souhaitez vous y appliquer, peut-on le réutiliser en licence LGPL?

Cordialement,
Phil.

**Comment by lauterry** [comment]
Bonjour

Vous pouvez le réutiliser. Pas de souci.
